export const AUTH_USER_SUCCESSFUL = 'AUTH_USER_SUCCESS';
export const AUTH_SIGNUP_SUCCESSFUL = 'AUTH_SIGNUP_SUCCESSFUL';
export const AUTH_USER_SIGN_IN = 'AUTH_USER_SIGN_IN';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const ERROR_CREATE_TALK = 'ERROR_CREATE_TALK';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_COMMENT_BY_ID = 'GET_COMMENT_BY_ID';



export const DELETE_USER_COMMENT_BY_ID = 'DELETE_USER_TALK_BY_ID';



export const TOPIC_LIST_FILL = 'TOPIC_LIST_FILL';
export const POST_LIST_FILL = 'POST_LIST_FILL';
export const CATEGORY_LIST_FILL = 'CATEGORY_LIST_FILL';
export const CREATE_POST = 'SEND_POST';
export const CREATE_TOPIC = 'CREATE_TOPIC';